export const p_list = [
  { value: "김윤호", label: "김윤호" },
  { value: "김준호", label: "김준호" },
  { value: "변성준", label: "변성준" },
  { value: "서동호", label: "서동호" },
  { value: "서희진", label: "서희진" },
  { value: "손준오", label: "손준오" },
  { value: "송혜근", label: "송혜근" },
  { value: "신재룡", label: "신재룡" },
  { value: "양륜관", label: "양륜관" },
  { value: "양재원", label: "양재원" },
  { value: "양현준", label: "양현준" },
  { value: "염지민", label: "염지민" },
  { value: "유지연", label: "유지연" },
  { value: "윤만성", label: "윤만성" },
  { value: "윤세림", label: "윤세림" },
  { value: "이재희", label: "이재희" },
  { value: "정찬훈", label: "정찬훈" },
  { value: "주서현", label: "주서현" },
  { value: "차유민", label: "차유민" },
  { value: "최정은", label: "최정은" },
  { value: "허윤", label: "허윤" },
];
